### ISSUE TITLE
Clarify timestamps

### ISSUE THREAD

**Issue by tschmidtb51** [openvex/spec#18]
The structure currently lists only one `timestamp` in the VEX document and one in the VEX statement. However, the community paper lists a `first_issued` and `last_updated` for each. I'm a bit confused which date goes where as theoretically 2 are sufficient (based on inheritance). Please update the description to clarify the usage...

**Comment by luhring** [comment]
cc: @puerco

**Comment by puerco** [comment]
Thanks for the issue Thomas, this should be handled by https://github.com/openvex/spec/pull/25
