### ISSUE TITLE
Ability to refer back to an SBOM?

### ISSUE THREAD

**Issue by rnjudge** [openvex/spec#28]
Is there currently a way for openvex to refer back to an SBOM? Right now it is common that you might refer to an openvex document from an SBOM, but does openvex support the inverse relationship?

**Comment by jspeed-meyers** [comment]
I'm also curious. I reviewed the [spec](https://github.com/openvex/spec/blob/main/OPENVEX-SPEC.md), especially the [document struct fields](https://github.com/openvex/spec/blob/main/OPENVEX-SPEC.md#document-struct-fields) and did not see a field that ties an an OpenVEX VEX document to an SBOM. Hmmm...

@puerco or @luhring, any thoughts?

**Comment by puerco** [comment]
Rose can you explain a bit more how you imagine this working?

I'm thinking to draft a proposal to expand `product` similar to [this idea in the vulnerability field](https://github.com/openvex/spec/issues/12#issuecomment-1590503038), this would let it use IRIs to point to elements in other documents, but perhaps you are thinking something else.

There has been a ton of feedback on the product field and I want to capture all needs and ideas in the next proposal to improve it

**Comment by puerco** [comment]
To anyone following this is one of the issues that went into the just released [v0.20 spec revision](https://github.com/openvex/spec/releases/tag/v0.2.0). The product field in the vex statement now takes an IRI which can point to components in SBOMs. This can make the vex statement rely 100% on an entry in an external document. 

The next release of the OpenVEX tooling will have strong support to read SBOMs as part of the document VEX processing logic. It will make use of these new fields. Thanks for pointing this out  @rnjudge :)
